### 쿠폰발행

POST http://localhost:8080/v1/issue
Content-Type: application/json

{
  "userId": 1,
  "couponId": 5
}

### 쿠폰발행 (redis)

POST http://localhost:8080/v1/issue-async
Content-Type: application/json

{
  "userId": 1,
  "couponId": 2
}
