### 쿠폰발행

POST http://localhost:8080/v1/issue
Content-Type: application/json

{
  "userId": 1,
  "couponId": 1
}

### 쿠폰발행 (redis)

POST http://localhost:8080/v2/issue-async
Content-Type: application/json

{
  "userId": 2,
  "couponId": 1
}
